# Generated by Django 4.2.7 on 2024-02-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckboxStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, unique=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
