# Generated by Django 4.2.7 on 2024-02-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_app', '0002_checkboxstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name_enabled', models.BooleanField(default=False)),
                ('asin_enabled', models.BooleanField(default=False)),
                ('category_enabled', models.BooleanField(default=False)),
                ('title_enabled', models.BooleanField(default=False)),
                ('mrp_enabled', models.BooleanField(default=False)),
                ('price_enabled', models.BooleanField(default=False)),
                ('shipping_price_enabled', models.BooleanField(default=False)),
                ('manufacturer_enabled', models.BooleanField(default=False)),
                ('star_rating_enabled', models.BooleanField(default=False)),
                ('is_prime_enabled', models.BooleanField(default=False)),
                ('customer_review_enabled', models.BooleanField(default=False)),
                ('weight_enabled', models.BooleanField(default=False)),
                ('color_enabled', models.BooleanField(default=False)),
                ('size_enabled', models.BooleanField(default=False)),
                ('package_dimensions_enabled', models.BooleanField(default=False)),
                ('item_model_number_enabled', models.BooleanField(default=False)),
                ('department_enabled', models.BooleanField(default=False)),
                ('date_first_available_enabled', models.BooleanField(default=False)),
                ('best_sellers_rank_enabled', models.BooleanField(default=False)),
                ('bullet_points_enabled', models.BooleanField(default=False)),
                ('image_urls_enabled', models.BooleanField(default=False)),
                ('product_url_enabled', models.BooleanField(default=False)),
                ('vedio_links_enabled', models.BooleanField(default=False)),
                ('delivery_time_enabled', models.BooleanField(default=False)),
                ('description_enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Header Status',
            },
        ),
        migrations.DeleteModel(
            name='CheckboxStatus',
        ),
    ]
