# Generated by Django 4.2.7 on 2024-03-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_app', '0006_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeDataCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
