# Generated by Django 4.2.11 on 2024-03-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_app', '0007_scrapedatacount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagination_count', models.IntegerField(default=10)),
            ],
        ),
    ]
