# Generated by Django 4.2.11 on 2024-03-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_app', '0008_paginationsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paginationsettings',
            name='pagination_count',
            field=models.IntegerField(),
        ),
    ]
